apiVersion: v1
kind: Secret
metadata:
  name: ekai-api-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ekai.labels" . | nindent 4 }}
    component: backend
type: Opaque
stringData:
  CLERK_PUBLISHABLE_KEY: {{ .Values.api.secrets.CLERK_PUBLISHABLE_KEY | quote }}
  CLERK_SECRET_KEY: {{ .Values.api.secrets.CLERK_SECRET_KEY | quote }}
  DATABASE_URL: {{ .Values.api.secrets.DATABASE_URL | quote }}
  {{- if .Values.api.secrets.AWS_ACCESS_KEY_ID }}
  AWS_ACCESS_KEY_ID: {{ .Values.api.secrets.AWS_ACCESS_KEY_ID | quote }}
  {{- end }}
  {{- if .Values.api.secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.api.secrets.AWS_SECRET_ACCESS_KEY | quote }}
  {{- end }}
  {{- if .Values.api.secrets.DEFAULT_OBJECT_STORAGE_BUCKET_ID }}
  DEFAULT_OBJECT_STORAGE_BUCKET_ID: {{ .Values.api.secrets.DEFAULT_OBJECT_STORAGE_BUCKET_ID | quote }}
  {{- end }}
  {{- if .Values.api.secrets.FLEET_API_KEY }}
  FLEET_API_KEY: {{ .Values.api.secrets.FLEET_API_KEY | quote }}
  {{- end }}
